apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: munshi-dev

resources:
  - ../../base

patchesStrategicMerge:
  - auth-service-patch.yaml
  - api-gateway-patch.yaml
  - databases-patch.yaml

commonLabels:
  environment: development

images:
  - name: munshi-auth-service
    newTag: dev-latest
  - name: munshi-api-gateway
    newTag: dev-latest

replicas:
  - name: auth-service
    count: 1
  - name: api-gateway
    count: 1
  - name: auth-postgres
    count: 1
  - name: gateway-postgres
    count: 1