apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  {{- if .Values.linkerd.enabled }}
  annotations:
    linkerd.io/inject: {{ .Values.linkerd.inject.default }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "munshi.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    environment: {{ .Values.environment }}