apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "munshi.authServiceLabels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "munshi.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  password: {{ .Values.secrets.postgres.authPassword | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-gateway-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "munshi.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  password: {{ .Values.secrets.postgres.gatewayPassword | b64enc | quote }}