{{- if .Values.createSecrets | default false }}
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "munshi-platform.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.jwt_secret | b64enc | quote }}
{{- end }}