{{- range $name, $secret := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "munshi-platform.labels" $ | nindent 4 }}
type: {{ $secret.type | default "Opaque" }}
data:
  {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
---
{{- end }}